### ISSUE TITLE
Feature Request: Not Authorized State

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/snitch#3] opened 2015-06-24 11:35 UTC
> It would be very helpful to add a Not Authorized state and set it by default for all files and hosts then we would be able to filter only not authorized connections without the authorized or blocked states, making the listing more manageable and helping the web admin catch suspicious connections faster.
> https://wordpress.org/support/topic/feature-request-not-authorized-state

**Comment by swissspidy** [comment] 2015-06-29 15:31
Duplicate of #2

**Closed as completed by swissspidy** 2015-06-29 15:31 UTC
Labels: enhancement
